# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adriaan M. Dokter
subtitle: Migration ecology
email: amd427@cornell.edu
description: >- # this means to ignore newlines until "baseurl:"
  Personal webpage
url: https://adokter.github.io
baseurl: "/new_site"
twitter_username: AdriaanDokter
github_username: adokter
minimal_mistakes_skin: default
search: true

teaser: /assets/images/500x300.png

# Build settings
markdown: kramdown
# remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name    : "Adriaan M. Dokter"
  avatar  : "/assets/images/bio-photo.jpg"
  bio     : "I’m an ecologist studying migration and population dynamics of birds"
  location: "Ithaca, NY, USA"
  links:
    - label: "Cornell Lab of Ornithology"
      icon: "fas fa-fw fa-link"
      url: "https://www.birds.cornell.edu/home/staff/adriaan-dokter/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AdriaanDokter"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adokter"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AdriaanDokter"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adokter"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
